### ISSUE TITLE
Can mutation be safely ignored after sexual crossover?

### ISSUE THREAD

**Issue by mdalvi** [colgreen/sharpneat#28]
With reference to method `public NeatGenome CreateOffspring(NeatGenome parent, uint birthGeneration)` in NeatGenome.cs @[here](https://github.com/colgreen/sharpneat/blob/master/src/SharpNeatLib/Genomes/Neat/NeatGenome.cs#L253) I observed that **there is no call to** `offspring.Mutate();` post sexual crossover!

Is it safe to completely ignore mutation after sexual crossover?

**Comment by colgreen** [comment]
Hi. Yes that's intentional. Most genetic algorithms do this as far as I know, i.e. crossover produces a child (or children) that have a mixture of genes from two or more parent's, and no mutation is applied. In biology I guess mutations are most likely to occur at this point, so there is an argument for always performing mutation when we perform crossover, but that's not how I chose to do it, and I think that's typical of GAs in general.

**Comment by mdalvi** [comment]
@colgreen Thank you for your reply.
