### ISSUE TITLE
RbfFunctionRegressionExperiment

### ISSUE THREAD

**Issue by alin256** [colgreen/sharpneat#29]
Hi,

SharpNeat.Domains.FunctionRegression.RbfFunctionRegressionExperiment
does not load from the GUI.
I did not manage to find a matching class.
Was it renamed or removed?

**Comment by colgreen** [comment]
This class has now returned, with the slightly different name of RbfFnRegressionExperiment.

The current plan is to not have support for Radial Basis Function neurons in the next major release (from the refactor repository) so if you (or anyone else reading this) wants to experiment with RBF-NEAT then let me know.

Thanks for reporting the problem.

**Comment by alin256** [comment]
Is there an estimate on when the refactored version would be fully functional? I am looking for a neat library and want to know if I should use the current version or wait for the new one.

**Comment by colgreen** [comment]
Hi. If you want to use sharpneat my advice is to use the current version. If the new major version is released in time for you to use it then it should be relatively simple to move a task/domain from the old to the new version. Regarding timescales, I can't really give any guidance because I'm only able to work on it sporadically. Hope that helps.
